<a href="https://colab.research.google.com/github/Hyunsooooo/Pytorch-/blob/main/02_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# 선형회귀

## 선형회귀
선형 회귀 이론에 대해 이해하고, pytorch를 이용하여 선형 회귀 모델을 만들어 보겠습니다.
- Data Definition(데이터에 대한 이해)
> 학습할 데이터에 대해

- Hypothesis(가설) 수립
> 가설을 수립하는 방법에 대해

- Comput loss(손실 계산)
> 학습데이터를 이용해서 연속적으로 모델을 개선시키는데 이 때의 loss를 이용

- Gradient Descent(경사하강법)
> 학습을 위한 핵심 알고리즘인 경사하강법에 대해 이해

### Data Definition
공부한 시간과 점수에 대한 상관관계.

1) Training Dataset , Test Dataset


![대체 텍스트](https://wikidocs.net/images/page/53560/data_definition.PNG)

어떤 학생이 1시간 공부를 했더니 2점, 다른 학생이 2시간 공부를 했더니 4점, 또 다른 학생이 3시간을 공부했더니 6점을 맞았습니다. 그렇다면, ***내가 4시간을 공부한다면 몇 점을 맞을 수 있을까요?***

![대체 텍스트](https://wikidocs.net/images/page/53560/linear_regression.PNG)

2) 훈련 데이터셋의 구성

앞서 텐서에 대해 배웠는데, 모델을 학습시키기 위한 데이터는 파이토치의 텐서의 형태(torch.tensor)를 가지고 있어야 한다. 그리고 입력과 출력을 각기 다른 텐서에 저장할 필요가 있다. 이 때 보편적으로 입력x 출력y 로 표기한다.

여기서 x_train은 공부한 시간, y_train은 그에 맵핑되는 점수를 의

In [ ]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

![대체 텍스트](https://wikidocs.net/images/page/53560/tensor1.PNG)

이제 모델의 가설을 세워보겠습니다.

### 가설의 수립

머신 러닝에서 식을 세울 때 이 식을 가설이라 한다. 보통 머신 러닝에서 가설은 임의로 추측해서 세워보는 식일 수도 있고, 경험적으로 알고 있는 식일 수도 있다. 그리고 맞는 가설이 아니라고 판단되면 계속 수정해나가는 식이기도 하다.

선형 회귀의 가설은 이미 널리 알려져있으므로 고민이 필요 없다. 선형 회귀란 학습 데이터와 가장 잘 맞는 하나의 직선을 찾는 일이다. 이 때 선형 회귀의 가설(직선의 방정식)은 다음과 같은 형식을 가진다.
$y=Wx+b$

가설의 H를 따서 y대신 다음과 같이 표현하기도 한다.

$H(x)=Wx+b$

이때 $x$와 곱해지는 $W$를 가중치(Weight)라고 하며, $b$를 편향(bias)이라고 한다.

*   $W$ 와 $b$는 중학교 수학 과정인 직선의 방정식에서 기울기와 y절편에 해당된다.
*   직선의 방정식 링크 : https://mathbang.net/443



### 비용함수(cost function)에 대한 이해

**비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)**

비용함수에 대한 이해를 돕기 위한 예제
4개의 훈련데이터와 이를 2차원 그래프에 4개의 점으로 표현한 상태
![대체 텍스트](https://wikidocs.net/images/page/53560/%EA%B7%B8%EB%A6%BC1.PNG)

목표는 4개의 점을 가장 잘 표현하는 직선을 그리는 것 다음 3개의 직선 중 가장 잘 표현한 것은?
![대체 텍스트](https://wikidocs.net/images/page/53560/%EA%B7%B8%EB%A6%BC2.PNG)

검은색 직선의 4개의 점에 가장 가깝다는 느낌이 든다.
-> 이를 수학적으로 표현하기 위해 error(오차)라는 개념을 도입

![대체 텍스트](https://wikidocs.net/images/page/53560/%EA%B7%B8%EB%A6%BC3.PNG)

위 그림은 실제값과 예측값에 대한 차이를 빨간색 화살표로 표현한 것. 이를 error라고 할 수 있다.


|$hours(x)$|2|3|4|5|
|:-|:-|:-|:-|:-|
|실제값|25|50|42|61|
|예측값|27|40|53|66|
|오차|-2|10|-11|-5|


총 오차(total error)를 구할 때에는 각 오차를 제곱한 뒤 전부 더해준다

*제곱하지 않고 더하면 음수와 양수를 더하게 되므로 제대로 된 오차의 크기를 측정할 수 없다.*


이를 수식으로 표현하게 되면

$\sum_{i=1}^{n}[y^{(i)} - H(x^{(i)})]^{2} = (-2)^{2}+(10)^{2}+(-11)^{2}+(-5)^{2} = 250$

여기서 n은 갖고 있는 데이터의 크기.

오차의 제곱합을 n으로 나누면 평균 제곱 오차(Mean squered Error, MSE)

$\frac{1}{n}\sum_{i=1}^{n}[y^{(i)} - H(x^{(i)})]^{2} = 250/4 = 62.5$

평균 제곱 오차를 $W$ 와 $b$에 의한 비용 함수(Cost function)로 재정의해보면

$cost(W,b) = \frac{1}{n}\sum_{i=1}^{n}[y^{(i)} - H(x^{(i)})]^{2}$

$Cost(W,b)$를 최소가 되게 만드는 $W$와 $b$를 구하면 훈련 데이터를 가장 잘 나타내는 직선을 구할 수 있다.


### 옵티마이저 - 경사 하강법(Gradient Descent)

앞서 정의한 비용 함수(Cost Function)의 값을 최소로 하는 W와 b를 찾는 방법에 대해. 이때 사용되는 것이 옵티마이저 알고리즘. 최적화 알고리즘이라고도 함. 그리고 이 옵티마이저 알고리즘을 통해 적절한 W와 b를 찾아내는 과정을 머신 러닝에서 학습(training)이라고 부름. 여기서 가장 기본적인 옵티마이저 알고리즘인 경사하강법에 대해.

편향 b에 대해 고려하지 않은 b=0 인 y = Wx와 같은 식을 기준으로 설명.

![대체 텍스트](https://wikidocs.net/images/page/53560/%EA%B7%B8%EB%A6%BC4.PNG)

가중치 $W$가 직선의 방정식에서는 기울기였음을 기억. 이제 $W$를 기울기라고 명명하고 설명.

위의 그림에서 주황색선은 기울기 $W$가 20일 때, 초록색선은 기울기 $W$가 1일 때를 보여줌.↕는 각 점에서의 실제값과 두 직선의 예측값과의 오차를 보여줌. 이는 앞서 예측에 사용했던 $y=13x+1$ 직선보다 확연히 큰 오차값들. 즉, 기울기가 지나치게 크면 실제값과 예측값의 오차가 커지고, 기울기가 지나치게 작아도 실제값과 예측값의 오차가 커짐.

설명의 편의를 위해 편향 $b$가 없이 단순히 가중치 $W$만을 사용한 $H(x)=Wx$라는 가설을 가지고, 경사 하강법을 설명. 비용 함수의 값 $cost(W)$는 cost라고 줄여서 표현. 이에 따라 $W$와 cost의 관계를 그래프로 표현하면.

![대체 텍스트](https://wikidocs.net/images/page/21670/%EA%B8%B0%EC%9A%B8%EA%B8%B0%EC%99%80%EC%BD%94%EC%8A%A4%ED%8A%B8.PNG)

기계는 임의의 초기값 W값을 정한뒤, 맨 아래 볼록한 부분을 향해 점차 W의 값을 수정. 그리고 이를 가능하게 하는 것이 경사 하강법.

![대체 텍스트](https://wikidocs.net/images/page/21670/%EC%A0%91%EC%84%A0%EC%9D%98%EA%B8%B0%EC%9A%B8%EA%B8%B01.PNG)

초록색 선은 W가 임의의 값을 가지는 네 가지 경우에 대해서, 그래프 상의 접선의 기울기를 보여줌. 여기서 맨 아래로 갈 수록 접선의 기울기가 점차 작아짐. 맨 아래의 볼록한 부분에서는 0 이 됨.

즉, cost의 최소 지점은 접선의 기울기가 0이 되는 지점이며, 미분값이 0이 되는 지점. 경사 하강법의 아이디어는 비용 함수를 미분하여 현재 W에서의 접선의 기울기를 구하고 접선의 기울기가 낮은 방향으로 W의 값을 변경하는 작업을 반복.

이 반복 작업에는 현재 W의 접선의 기울기를 구해 특정 숫자 α를 곱한 값을 빼서 새로운 W로 사용한다.

기울기$ = \frac{\partial cost(W)}{\partial W}$

*   기울기가 음수일 때 : $W$의 값이 증가
> W:=W−α×(음수기울기)=W+α×(양수기울기)


*   기울기가 양수일 때 : W의 값이 감소
> W:=W−α×(양수기울기)

W:=W−α$\frac{\partial }{\partial W}cost(W)$

여기서 학습률(learning rate)라 하는 α는 어떤 의미인가. α는 W의 값을 변경할 때, 얼마나 크게 변경할지를 정함. 또는 W를 그래프의 한 점으로 보고 접선의 기울기가 0이 될 때 까지 경사를 따라 내려간다는 관점으로 보면, 얼마나 큰 폭으로 이동할 지를 정함. 학습률 α를 무작정 크게 하면 금방 접선의 기울기가 최소가 되는 W 값을 찾을 것 같지만 그렇지 않다.

![대체 텍스트](https://wikidocs.net/images/page/21670/%EA%B8%B0%EC%9A%B8%EA%B8%B0%EB%B0%9C%EC%82%B0.PNG)

위의 그림은 학습률 α가 지나치게 높은 값을 가질 때, 접선의 기울기가 0이 되는 W값을 찾는 게 아니라 W값이 발산하는 상황을 보여준다. 반대로 α가 너무 낮으면 학습 속도가 느려지므로 적당한 α 값을 차즌ㄴ 것이 중요하다.

실제 경사 하강법은 W와 b에 대해서 동시에 경사하강법을 수행하며 최적의 W와 b 값을 찾아간다.

- 가설, 비용함수, 옵티마이저는 머신 러닝 분야에서 사용되는 포괄적 개념.. 풀고자 하는 문제에 따라 가설, 비용함수, 옵티마이저는 전부 다를 수 있으며 선형 회귀에 가장 적합한 비용 함수는 평균 제곱 오차, 옵티마이저는 경사 하강법임.

이제 파이토치로 구현하기.



### 파이토치로 선형 회귀 구현하기
실습을 위해 파이토치의 도구들을 import

1) 기본 세팅

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드를 준다.

torch.manual_seed(1)

실습을 위한 기본적인 세팅 끝, 훈련 데이터 x_train , y_train 선언

2) 변수 선언

In [ ]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

x_train , y_train 의 크기 출력

In [ ]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


3) 가중치와 편향의 초기화
선형 회귀란 학습 데이터와 가장 잘 맞는 직선을 찾는 일. W와 b로 정의가 된다. 따라서 선형 회귀의 목표는 가장 잘 맞는 직선을 정의하는 W와 b를 찾는 것

가중치 W를 0으로 초기화 하고, 값을 출력해봄.

In [ ]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시.
W = torch.zeros(1, requires_grad=True)
#가중치 W 출력
print(W)

tensor([0.], requires_grad=True)


가중치 W가 0임, 여기서 requires_grad =True 가 인자로 주어짐. 이는 이 변수는 학습을 통해서 계속 값이 변경되는 변수임을 의미.

b도 0으로 초기화하고, 학습을 통해 값이 변경되는 변수임을 명시.

In [ ]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


현재 가중치 W,b 둘다 0이므로 직선의 방정식은

$y=0*x+0$

지금 상태에선 x에 어떤 값이 들어가도 가설은 0을 예측함
즉  적절한 W,b 값이 아님



4) 가설 세우기

파이토치 코드 상으로 직선의 방정식에 해당되는 가설을 선언

$H(x) = Wx+b$


In [ ]:
hypothesis= x_train*W +b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


5) 비용 함수 선언
파이토치 상으로 선형 회귀의 비용 함수에 해당되는 평균 제곱 오차를 선언

$cost(W,b) = \frac{1}{n}\sum_{i=1}^{n}[y^{(i)} - H(x^{(i)})]^{2}$


In [ ]:
# 앞서 배운 torch.mean 으로 평균을 구함
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


6) 경사 하강법 구현하기

SGD 는 경사 하강법의 일종임, lr 는 learning rate를 의미 학습 대상인 W와 b가 SGD 에 입력됨.

In [ ]:
optimizer = optim.SGD([W,b], lr = 0.01)

optimizer.zero_grad()를 실행함으로써 미분을 통해 얻은 기울기를 0으로 초기화. 기울기를 초기화해야 새로운 가중치 편향에 대해서 새로운 기울기를 구할 수 있다. 그 다음 cost.backward() 함수를 호출하면 가중치 W와 편향 b에 대한 기울기가 계산됨. 그 다음 경사 하강법의 최적화 함수 optimizer의 .step() 함수를 호출하여 인수로 들어갔던 W와 b에서 리턴되는 변수들의 기울기에 lr 을 곱하여 빼줌으로서 업데이트함.

In [ ]:
# gradient 를 0으로 초기화
optimizer.zero_grad()
#비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

7) 전체 코

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W,b], lr= 0.01)

nb_epochs = 2000 #경사 하강법의 실행 횟수
for epoch in range(nb_epochs+1):
  # H(x) 계산
  hypothesis= x_train*W +b

  #cost
  cost = torch.mean((hypothesis-y_train)**2)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #100번 마다 로그 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

최종 훈련 결과를 보면 최적의 기울지 W 는 2에 가깝고 b는 0에 가깝다 데이터를 보면 실제 정답이 W=2 ,b=0 인걸 보면 거의 근사하다.

## 자동 미분 (Autograd)

경사 하강법 코드엔 requries_grad=True, backward() 등이 나오는데 파이토치에서 제공하는 자동미분 기능을 수행하는 것이다.

### 경사 하강법 리뷰



![대체 텍스트](https://wikidocs.net/images/page/21670/%EC%A0%91%EC%84%A0%EC%9D%98%EA%B8%B0%EC%9A%B8%EA%B8%B01.PNG)

경사 하강법은 비용 함수를 미분하여 이 함수의 기울기(gradient)를 구해서 비용이 최소화 되는 방향을 찾아내는 알고리즘

모델이 복잡해질 수록 경사 하강법을 넘파이 등으로 직접 코딩하기 어렵다.
파이토치에선 이런 수고를 덜기 위해 자동미분(Autograd)를 지원함.

###자동 미분 실습하기

자동 미분 실습. 임의로 $2w^2+5$ 라는 식을 세워보고 , $w$에 대해 미분해본다.
값이 2인 임의의 스칼라 텐서 w 선언, 이때 requries_grad 를 True로 설정. 이는 이 텐서에 대한 기울기를 저장하겠다는 의미. 이렇게 하면 w.grad 에 w에 대한 미분값이 저장

In [ ]:
w = torch.tensor(2.0, requires_grad=True)

In [ ]:
#수식

y = w**2
z= 2*y +5

In [ ]:
#해당 수식을 w에 대해 미분해야한다. .backward()를 호출하면 해당 수식의 w에 대한 기울기를 계산한다.

z.backward()

In [ ]:
#이제 w.grad를 출력하면 w가 속한 수식을 w로 미분한 값이 저장된다

print(f'수식을 w로 미분한 값: {w.grad}')

수식을 w로 미분한 값: 8.0


## 다중 선형회귀

앞서 배운 x가 1개인 선형 회귀를 단순선형회귀라 하고, 다수의 x로부터 y를 예측하는 것을 다중선형회귀라 한다.

### 데이터에 대한 이해

다음과 같은 훈련 데이터가 있다. 단순 선형 회귀와 다른 점은 독립 변수 x의 갯수가 3개이다.

![대체 텍스트](https://wikidocs.net/images/page/54841/%ED%9B%88%EB%A0%A8%EB%8D%B0%EC%9D%B4%ED%84%B0.PNG)

독립 변수 x가 3개이므로 이를 수식으로 표현하면

$H(x)=w_1x_1+w_2x_2+w_3x_3+b$

### 파이토치로 구현하기

훈련 데이터에 대한 선언

$H(X) = w_{1}x_{1} + w_{2}x_{2} + w_{3}x_{3}+b$

In [ ]:
# 훈련 데이터

x1_train = torch.FloatTensor([[73],[93],[89],[96],[73]])
x2_train = torch.FloatTensor([[80],[88],[91],[98],[66]])
x3_train = torch.FloatTensor([[75],[93],[90],[100],[70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [ ]:
# 가중치 w와 편향 b를 선언한다. w도 3개임

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
# optimizer 설정

optimizer = optim.SGD([w1,w2,w3,b], lr = 1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
  # H(x)
  hypothesis = x1_train*w1 + x2_train*w2 + x3_train*w3  + b

  # cost
  cost = torch.mean((hypothesis - y_train)**2)

  # cost 로 H(x) 개선

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번마다 로그 출력

  if epoch %100 == 0:
     print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))


Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


### 벡터와 행렬 연산으로 바꾸기 

위의 코드를 개선할 수 있음. x의 갯수가 3개였으니까, x1_train, x2_train, x3_train, w1, w2 ,w3 를 일일히 선언해줬는데 1000개라고 하면 너무 번거롭다. 이를 해결하기 위해 행렬 곱셉 연산(벡터의 내적)을 사용한다.
- 행렬의 곱셈 과정에서 이루어지는 벡터 연산을 벡터 내적(Dot Product)라고 한다.

![대체 텍스트](https://wikidocs.net/images/page/54841/%ED%96%89%EB%A0%AC%EA%B3%B1.PNG)


1) 벡터 연산으로 이해하기

![대체 텍스트](https://wikidocs.net/images/page/54841/%EB%82%B4%EC%A0%81.PNG)

두 벡터를 각각 $X$와 $W$로 표현한다면, 가설은 다음과 같습니다.

$H(X)=XW$

$x$의 개수가 3개였음에도 이제는 $X$와 $W$라는 두 개의 변수로 표현된 것을 볼 수 있습니다.

2) 행렬 연산으로 이해하기

![대체 텍스트](https://wikidocs.net/images/page/54841/%ED%9B%88%EB%A0%A8%EB%8D%B0%EC%9D%B4%ED%84%B0.PNG)

전체 훈련 데이터의 개수를 셀 수 있는 1개의 단위 = sample 이라고 한다. 현재 샘플의 수는 5개이다. 각 샘플에서 y를 결정하게 하는 각각의 독립변수 x 를 특성(feature)이라고 한다.
현재 특성은 3개이다.

이는 종속 변수 x 들의 수가 (sample * feature) = 15개임을 의미한다.


$\left(
    \begin{array}{c}
      x_{11}\ x_{12}\ x_{13}\ \\
      x_{21}\ x_{22}\ x_{23}\ \\
      x_{31}\ x_{32}\ x_{33}\ \\
      x_{41}\ x_{42}\ x_{43}\ \\
      x_{51}\ x_{52}\ x_{53}\ \\
    \end{array}
  \right)$

  그리고 여기에 가중치 $w_{1}, w_{2}, w_{3}$을 원소로 하는 벡터를 $W$라 하고 이를 곱해보겠습니다.

$\left(
    \begin{array}{c}
      x_{11}\ x_{12}\ x_{13}\ \\
      x_{21}\ x_{22}\ x_{23}\ \\
      x_{31}\ x_{32}\ x_{33}\ \\
      x_{41}\ x_{42}\ x_{43}\ \\
      x_{51}\ x_{52}\ x_{53}\ \\
    \end{array}
  \right)
\left(
    \begin{array}{c}
      w_{1} \\
      w_{2} \\
      w_{3} \\
    \end{array}
  \right)
\  =
\left(
    \begin{array}{c}
      x_{11}w_{1}+ x_{12}w_{2}+ x_{13}w_{3}\ \\
      x_{21}w_{1}+ x_{22}w_{2}+ x_{23}w_{3}\ \\
      x_{31}w_{1}+ x_{32}w_{2}+ x_{33}w_{3}\ \\
      x_{41}w_{1}+ x_{42}w_{2}+ x_{43}w_{3}\ \\
      x_{51}w_{1}+ x_{52}w_{2}+ x_{53}w_{3}\ \\
    \end{array}
  \right)$

  위의 식은 결과적으로 다음과 같습니다.

$H(X) = XW$

이 가설에 각 샘플에 더해지는 편향 $b$를 추가해봅시다. 샘플 수만큼의 차원을 가지는 편향 벡터 $B$를 만들어 더합니다.

$\left(
    \begin{array}{c}
      x_{11}\ x_{12}\ x_{13}\ \\
      x_{21}\ x_{22}\ x_{23}\ \\
      x_{31}\ x_{32}\ x_{33}\ \\
      x_{41}\ x_{42}\ x_{43}\ \\
      x_{51}\ x_{52}\ x_{53}\ \\
    \end{array}
  \right)
\left(
    \begin{array}{c}
      w_{1} \\
      w_{2} \\
      w_{3} \\
    \end{array}
  \right)
+
\left(
    \begin{array}{c}
      b \\
      b \\
      b \\
      b \\
      b \\
    \end{array}
  \right)
 \ =
\left(
    \begin{array}{c}
      x_{11}w_{1}+ x_{12}w_{2}+ x_{13}w_{3} + b\ \\
      x_{21}w_{1}+ x_{22}w_{2}+ x_{23}w_{3} + b\ \\
      x_{31}w_{1}+ x_{32}w_{2}+ x_{33}w_{3} + b\ \\
      x_{41}w_{1}+ x_{42}w_{2}+ x_{43}w_{3} + b\ \\
      x_{51}w_{1}+ x_{52}w_{2}+ x_{53}w_{3} + b\ \\
    \end{array}
  \right)$

위의 식은 결과적으로 다음과 같습니다.

$H(X)=XW+B$

결과적으로 전체 훈련 데이터의 가설 연산을 3개의 변수만으로 표현하였습니다.
이와 같이 벡터와 행렬 연산은 식을 간단하게 해줄 뿐만 아니라 다수의 샘플의 병렬 연산이므로 속도의 이점을 가집니다.

이를 참고로 파이토치로 구현해봅시다.


3) 행렬 연산을 고려하여 파이토치로 구현

In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91 ,90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [ ]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [ ]:
# 가중치와 편햔 선언

W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad= True)

In [ ]:
hypothesis = x_train.matmul(W)+b

In [ ]:
# 가설을 행렬곱으로 간단히 정의

In [ ]:
# 데이터 선언
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

# 모델 초기화
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W,b], lr = 1e-5)


nb_epochs = 20
for epoch in range(nb_epochs+1):
  # H(x)
  hypothesis = x_train.matmul(W) +b

  #cost

  cost = torch.mean((hypothesis-y_train)**2)

  # cost 로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
  ))


Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371063
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo

## nn.Module 로 구현하는 선형 회귀

이전까지는 선형 회귀를 좀 더 직접적으로 이해하기 위해 가설, 비용 함수를 직접 정의해서 선형 회귀 모델을 구현했다. 이번에는 파이토치에서 이미 구현되어 제공되고 있는 함수들을 불러 오는 것으로 더 쉽게 선형 회귀 모델을 구현

ex, 파이토치에서는 선형 회귀 모델이 nn.Linear() 라는 함수로, 또 평균제곱오차가 nn.functional.mse_loss() 라는 함수로 구현되어져 있다.

### 2.4.1. 단순 선형 회귀 구현

데이터를 선언. 아래 데이터는  y= 2x 를 가정된 상태에서 만들어진 데이터로 우리는 이미 정답이 W=2, b=0 이라는 사실을 알고 있는 상태. 모델이 이  두 W와 b의 값을 제대로 맞히도록 하는 것이 목표

In [ ]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
#data

In [ ]:
# 선형 회귀 모델 구현. nn.Linear()는 입력의 차원, 출력의 차원을 인수로 받는다.
# 모델을 선언 및 초기화, 단순 선형 회귀이므로 input_dim=1, output_dim = 1

model = nn.Linear(1,1)

model 에는 가중치 W와 편향 b가 저장되어 있는데 이 값은 model.parameters() 라는 함수를 사용하여 불러 올 수 있다.

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5047]], requires_grad=True), Parameter containing:
tensor([0.4902], requires_grad=True)]


2개의 값이 출력되는데 첫번 째 값이 W고 두 번째 값이 b 이다. 두 값 모두 현재는 랜덤 초기화가 되어 있는데 두 값 모두 학습의 대상이므로 requires_grad = True 가 돼있다.
이제 옵티마이저를 정의한다. model.parameters()를 사용하여 W와 b를 전달한다. lr = 0.01로 정의

In [ ]:
# optimizer 설정. 경사 하강법 SGD 를 사용하고, lr를 0.01

optimizer= torch.optim.SGD(model.parameters(), lr= 0.01)

In [ ]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복

nb_epochs = 2000
for epoch in range(nb_epochs+1):

  #H(x) 계산
  prediction = model(x_train)

  # cost 계산

  cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균제곱 오차 함수

  #cost로 H(x) 개선
  # gradient 를 0으로 초기화

  optimizer.zero_grad()
  # 비용 함수를 미분하여 gradient 계산
  cost.backward() # backward 연산
  # W와 b를 업데이트
  optimizer.step()

  if epoch %100 == 0 :
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 7.743174
Epoch  100/2000 Cost: 0.082010
Epoch  200/2000 Cost: 0.050677
Epoch  300/2000 Cost: 0.031315
Epoch  400/2000 Cost: 0.019351
Epoch  500/2000 Cost: 0.011958
Epoch  600/2000 Cost: 0.007389
Epoch  700/2000 Cost: 0.004566
Epoch  800/2000 Cost: 0.002822
Epoch  900/2000 Cost: 0.001744
Epoch 1000/2000 Cost: 0.001077
Epoch 1100/2000 Cost: 0.000666
Epoch 1200/2000 Cost: 0.000411
Epoch 1300/2000 Cost: 0.000254
Epoch 1400/2000 Cost: 0.000157
Epoch 1500/2000 Cost: 0.000097
Epoch 1600/2000 Cost: 0.000060
Epoch 1700/2000 Cost: 0.000037
Epoch 1800/2000 Cost: 0.000023
Epoch 1900/2000 Cost: 0.000014
Epoch 2000/2000 Cost: 0.000009


학습이 완료. cost의 값이 매우 작다. W와 b의 값도 보자.

In [ ]:
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print('훈련 후 입력이 4일 때의 예측값 :', pred_y)


훈련 후 입력이 4일 때의 예측값 : tensor([[7.9941]], grad_fn=<AddmmBackward>)


이 문제의 정답은 W가 2이므로 어느정도 최적화가 됐다 볼 수 있다. 실제 예측값은 8에 매우 가깝다 이제 학습 후의 W와 b를 출력해보겠

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9966]], requires_grad=True), Parameter containing:
tensor([0.0078], requires_grad=True)]


W 의 값이 2에 가깝고, b의 값이 0에 가까운 것을 볼 수 있다.
- H(x) 식에 입력 x로부터 예측된 y를 얻는 것을 forward 연산이라고 한다.
- 학습 전 , prediction = model(x_train)은 x_train 으로부터 예측값을 리턴하므로 forward 연산이다.
- 학습 후 ,pred_y = model(new_var)는 임의의 값 new_var로부터 예측값을 리턴하므로 forward 연산.
- 학습과정에서 비용 함수를 미분하여 기울기를 구하는 것을 backward 연산이라고 한다.
- cost.backward() 는 비용 함수로부터 기울기를 구하라는 의미이며 backward 연산이다.

### 2.4.2 다중 선형 회귀 구현하기

이제 nn.Linear()와 nn.functional.mse_loss() 로 다중 선형 회귀를 구현해보자. 사실 코드 자체는 달라진 게 거의 없는데, nn.Linear() 의 인자값과 lr만 조절했다.

데이터를 선언한다. 3개의 x로부터 하나의 y를 예측하는 문제이다. 가설 수식은 $H(x) = w_{1}x_{1} + w_{2}x_{2} + w_{3}x_{3} + b$입니다.

In [ ]:
x_train = torch.FloatTensor([[73,80,75],
                             [93, 88, 93],
                            [89,91, 90],
                            [96,98,100],
                            [73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [ ]:
# 선형 회귀 구현

In [ ]:
# 모델을 선언 및 초기화, 다중 선형 회귀이므로 input_dim =3 , output_dim = 1
model = nn.Linear(3,1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.3571,  0.5140, -0.2947]], requires_grad=True), Parameter containing:
tensor([-0.5325], requires_grad=True)]


In [ ]:
# 첫번 째는 W의 값들, 두 번째는 b의 값, 현재는 모두 랜덤 초기화 된 상태. requires = True, 학습의 대상이라는 것

# 옵티마이저 정의. model.parameters 를 사용하여 3개의 w와 b를 전달한다. lr = 0.00001 로 정의한다.

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
  # H(x) 계산
  prediction = model(x_train)
  #model(x_train) = model.forward(x_train)

  # cost 계산
  cost= F.mse_loss(prediction, y_train)

  # cost 로 H(x) 개선
  # gradient 를 0으로 초기화
  optimizer.zero_grad()
  # 비용 함수를 미분하여 gradient 계산
  cost.backward()
  optimizer.step() # W와 b를 업데이트

  if epoch % 100 ==0:
    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 34178.914062
Epoch  100/2000 Cost: 12.461840
Epoch  200/2000 Cost: 11.817289
Epoch  300/2000 Cost: 11.206689
Epoch  400/2000 Cost: 10.628275
Epoch  500/2000 Cost: 10.080351
Epoch  600/2000 Cost: 9.561388
Epoch  700/2000 Cost: 9.069703
Epoch  800/2000 Cost: 8.604002
Epoch  900/2000 Cost: 8.162824
Epoch 1000/2000 Cost: 7.744920
Epoch 1100/2000 Cost: 7.349029
Epoch 1200/2000 Cost: 6.974030
Epoch 1300/2000 Cost: 6.618781
Epoch 1400/2000 Cost: 6.282284
Epoch 1500/2000 Cost: 5.963500
Epoch 1600/2000 Cost: 5.661542
Epoch 1700/2000 Cost: 5.375480
Epoch 1800/2000 Cost: 5.104517
Epoch 1900/2000 Cost: 4.847822
Epoch 2000/2000 Cost: 4.604651


In [ ]:
# 학습 완료, Cost 의 값이 매우 작다. 3개의 W와 b도 확인해보자. x에 임의의 값 [73,80,75]를 넣어 모델이 예측하는 y의 값을 보자

In [ ]:
#임의의 입력 선언
new_var = torch.FloatTensor([[73,80,75]])

# 입력한 값 [73,80,75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75일 때의 예측값: ' , pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값:  tensor([[154.2830]], grad_fn=<AddmmBackward>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.6169, 0.9175, 0.4849]], requires_grad=True), Parameter containing:
tensor([-0.5207], requires_grad=True)]


## 2.5 클래스로 파이토치 모델 구현하기

파이토치의 대부분 구현체들은 대부분 모델을 생성할 때 클래스(Class)를 사용하고 있다. 앞서 배운 선형 회귀를 ㄱ클래스로 구현한다. 앞서 구현한 코드와 다른 점은 오직 '클래스'로 모델을 구현했다는 

### 2.5.1. 모델을 클래스로 구현하기


In [ ]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로, input_dim = 1, output_dim = 1
model = nn.Linear(1,1)

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self,x):
    return self.linear(x)

In [ ]:
model = LinearRegressionModel()

위와 같은 클래스를 사용한 모델 구현 형식은 대부분의 파이토치 구현체에서 사용하고 있는 방식으로 반드시 숙지해야 한다.

클래스 형태의 모델을 nn.Module를 상속받는다. 그리고 init() 에서 모델의 구조와 동적을 정의하는 생성자를 정의한다. 이는 파이썬에서 객체가 갖는 속성값을 초기화하는 역할로, 객체가 생성될 때 자동으로 호출된다.

super() 함수를 부르면 여기서 만든 클래스는 nn.Module 클래스의 속성들을 가지고 초기화된다.

forward() 함수는 모델이 학습뎉이터를 입력받아 forward 연산을 진행시키는 함수
이 함수는 model 객체를 데이터와 함께 호출하면 자동으로 실행된다. 예를 들어 model 이란 이름의 이름의 객체를 생성 후 ,model(입력 데이터)와 같은 형식으로 객체를 호출하면 자동으로 forward 연산이 수행된다.

*   $H(x)$  식에 입력 $x$로부터 예측된 $y$를 얻는 것을 forward 연산이라고 합니다.

앞어 다중 선형 회귀 모델은 다음과 같이 구

In [ ]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim = 3 output_dim =1 

model = nn.Linear(3,1)

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

    def forward(self,x):
      return self.linear(x)

In [ ]:
model = MultivariateLinearRegressionModel()

### 2.5.2 단순 선형 회귀 클래스로 구현하기



In [ ]:
# 데이터

x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self,x):
    return self.linear(x)

In [ ]:
model = LinearRegressionModel()

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

  #H(x)
  prediction = model(x_train)

  # cost
  cost = F.mse_loss(prediction, y_train)

  # cost 로 H(x) 개선

  optimizer.zero_grad()

  cost.backward()

  optimizer.step()

  if epoch %100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.372701
Epoch  100/2000 Cost: 0.001315
Epoch  200/2000 Cost: 0.000812
Epoch  300/2000 Cost: 0.000502
Epoch  400/2000 Cost: 0.000310
Epoch  500/2000 Cost: 0.000192
Epoch  600/2000 Cost: 0.000118
Epoch  700/2000 Cost: 0.000073
Epoch  800/2000 Cost: 0.000045
Epoch  900/2000 Cost: 0.000028
Epoch 1000/2000 Cost: 0.000017
Epoch 1100/2000 Cost: 0.000011
Epoch 1200/2000 Cost: 0.000007
Epoch 1300/2000 Cost: 0.000004
Epoch 1400/2000 Cost: 0.000003
Epoch 1500/2000 Cost: 0.000002
Epoch 1600/2000 Cost: 0.000001
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000000
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
#다중 선형회귀 클래스로 구현하기

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])



class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)



model = MultivariateLinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 34730.640625
Epoch  100/2000 Cost: 0.382716
Epoch  200/2000 Cost: 0.373201
Epoch  300/2000 Cost: 0.364163
Epoch  400/2000 Cost: 0.355610
Epoch  500/2000 Cost: 0.347489
Epoch  600/2000 Cost: 0.339785
Epoch  700/2000 Cost: 0.332485
Epoch  800/2000 Cost: 0.325561
Epoch  900/2000 Cost: 0.318991
Epoch 1000/2000 Cost: 0.312752
Epoch 1100/2000 Cost: 0.306845
Epoch 1200/2000 Cost: 0.301232
Epoch 1300/2000 Cost: 0.295918
Epoch 1400/2000 Cost: 0.290865
Epoch 1500/2000 Cost: 0.286075
Epoch 1600/2000 Cost: 0.281538
Epoch 1700/2000 Cost: 0.277212
Epoch 1800/2000 Cost: 0.273119
Epoch 1900/2000 Cost: 0.269227
Epoch 2000/2000 Cost: 0.265536


## 2.6 미니 배치와 데이터 로드 

이번 채벝에서 배우는 내용은 선형 회귀에 한정되는 내용은 아니고 데이터를 로드하는 방법과 미니 배치 경사 하강법에 대해 학습한다.

### 2.6.1 미니 배치와 배치 크기


In [ ]:
# 앞서 다룬 데이터를 상기
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

위 데이터의 샘플의 개수는 5개이다. 전체 데이터를하나의 행렬로 선언하여 전체 데이터에 대해서 경사 하강법을 수행하여 학습할 수 있다. 근데 위 데이터는 현업에서 다루게 되는 방대한 데이터에 비하면 굉장히 적은 양이다. 만약 데이터가 수십만개 이상이면 전체 데이터에 대해 경사 하강법 하는 건 너무 오래 걸리고 많은 계산량이 필요하다.

그래서 전체 데이터를 더 작은 단위로 나눠 해당 단위로 학습하게 하는 개념이 나오게 됐는데, 이를 미니배치 라고 한다.

![대체 텍스트](https://wikidocs.net/images/page/55580/%EB%AF%B8%EB%8B%88%EB%B0%B0%EC%B9%98.PNG)

위의 그림은 전체 데이터를 미니 배치 단위로 나눈 것을 보여준다. 미니 배치 학습을 하게되면 미니 배치만큼만 가져가서 미니 배치에 대한 비용을 계산하고, 경사 하강법을 수행한다. 그리고 다음 미니 배치를 가져가서 경사 하강법을 수행하고 마지막 미니 배치까지 이를 반복한다. 이렇게 전체 데이터에 대한 학습이 1회 끝나면 1에포크가 끝난다.
- 에포크(epoch)는 전체 훈련 데이터가 학습에 한 번 사용된 주기를 의미한다.

미니 배치 학습에서는 미니 배치의 개수만큼 경사 하강법을 수행해야 전체 데이터가 한 번 전부 사용되어 1 에포크가 된다. 미니 배치의 개수는 결국 미니 배치의 '크기를 몇으로 하느냐에 달렸느넫, 미니 배치의 크기를 batch_size 라고 한다.
- 전체 데이터에 대해서 한 번에 경사 하강법을 수행하는 방법을 ' 배치 경사 하강법' 이라고 부른다. 반면 , 미니 배치 단위로 경사 하강법을 수행하는 것을' 미니 배치 경사 하강법' 이라고 부른다.
- 배치 경사 하강법은 전체 데이터를 사용하므로 가중치 값이 최적값에 수렴하는 과정이 매우 안정적이지만, 계산량이 너무 많다. 미니 배치 경사 하강법은, 일부만을 보고 수행하므로 최적값으로 수렴하는 과정에서 값이 조금 헤매기도 하지만 훈련 속도가 빠르다.

### 2.6.2 이터레이션 (Iteration)

![대체 텍스트](https://wikidocs.net/images/page/36033/batchandepochiteration.PNG)

위 그림은 에포크와 배치 크기와 이터레이션의 관계를 보여준다.

이터레이션은 한 번의 에포크 내에서 이루어지는 매개변수인 가중치 W와 b의 업데이트 횟수다. 전체 데이터가 2,000일 때 배치 크기를 200으로 하면 이터레이션은 10개이다. 에포크 당 업데이트가 10번 이루어짐을 의미한다.

이제 미니 배치 학습을 할 수 있도록 해주는 파이토치의 도구들을 알아보자

### 2.6.3 데이터 로드

파이토치에서는 데이터를 좀 더 쉽게 다룰 수 있도록 유용 한 도구로서 데이터셋과 데이터로더를 제공한다. 이를 사용하면 미니 배치 학습, 데이터 셔플, 병렬 처리까지 간단히 수행할 수 있다. 기본적인 사용 방법은 Dataset를 정의하고, 이를 DataLoader에 전달하는 것이다.


In [ ]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [ ]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [ ]:
# 이제 이를 TensorDataset 의 입력으로 사용하고 dataset으로 저장

In [ ]:
dataset = TensorDataset(x_train, y_train)

파이토치의 데이터셋을 만들었다면 데이터로더를 사용 가능하다. 데이터로더는 기본적으로 2개의 인자를 입력받는데, 하나의 데이터셋, 미니 배치의 크기다. 이때 미니 배치의 크기는 통상적으로 2의 배수를 사용한다. 그리고 추가적으로 많이 사용되는 인자로 shuffle이 있다. shuffle = True 를 선택하면 Epoch 마다 데이터셋을 섞어서 데이터가 학습되는 순서를 바꾼다.

사람도 같은 문제지를 계속 풀면 어느 순간 문제의 순서에 익숙해질 수 있다. 예를 들어 어떤 문제지의 12번 문제를 풀면서, '13번 문제가 뭔지는 기억은 안 나지만 어제 풀었ㅅ던 기억으로 5번이었떤 것 같은데' 하면서 문제 자체보단 순서에 익숙해질 수 있다. 그럴 때 문제지를 풀 때마다 순서를 랜덤으로 바꾸면 도움이 될 것이다. 마찬가지로 모델이 데이터셋의 순서에 익숙해지는 것을 방지하여 학습할 때는 이 옵션을 True로 주는 것을 권장한다.

In [ ]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [ ]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

이제 훈련을 진행한다. 아래 코드에서는 batch_idx 와 samples 를 주석 처리했는데 어떤 식으로 훈련되고 있는지 궁금하다면 주석 처리를 해제하고 훈련시켜보기 바람.

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 10411.642578
Epoch    0/20 Batch 2/3 Cost: 4858.296875
Epoch    0/20 Batch 3/3 Cost: 696.264954
Epoch    1/20 Batch 1/3 Cost: 302.164368
Epoch    1/20 Batch 2/3 Cost: 184.705536
Epoch    1/20 Batch 3/3 Cost: 53.354000
Epoch    2/20 Batch 1/3 Cost: 14.083602
Epoch    2/20 Batch 2/3 Cost: 7.733485
Epoch    2/20 Batch 3/3 Cost: 0.321681
Epoch    3/20 Batch 1/3 Cost: 4.963413
Epoch    3/20 Batch 2/3 Cost: 0.807077
Epoch    3/20 Batch 3/3 Cost: 12.778421
Epoch    4/20 Batch 1/3 Cost: 4.659064
Epoch    4/20 Batch 2/3 Cost: 3.110271
Epoch    4/20 Batch 3/3 Cost: 4.507976
Epoch    5/20 Batch 1/3 Cost: 3.470737
Epoch    5/20 Batch 2/3 Cost: 5.871498
Epoch    5/20 Batch 3/3 Cost: 2.471012
Epoch    6/20 Batch 1/3 Cost: 6.114941
Epoch    6/20 Batch 2/3 Cost: 3.034981
Epoch    6/20 Batch 3/3 Cost: 3.528511
Epoch    7/20 Batch 1/3 Cost: 3.834924
Epoch    7/20 Batch 2/3 Cost: 5.315554
Epoch    7/20 Batch 3/3 Cost: 3.515053
Epoch    8/20 Batch 1/3 Cost: 6.080107
Epoch    

In [ ]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[154.4468]], grad_fn=<AddmmBackward>)


## 2.7 커스텀 데이터셋(Custom Dataset)

앞 내용을 복습해보자. 파이토치에서는 데이터셋을 좀 더 쉽게 다룰 수 있도록 유용한 도구로서 , torch.utils.data.Dataset과 torch.utils.data.DataLoader를  제공한다. 이를 사용하면 미니 배치 학습, 데이터 셔플(shuffle) , 병렬 처리까ㅣ지 간단히 수행할 수 있다. 기본적인 사용 방법은 Dataset을 정의하고, 이를 DataLoader 에 ㄷ전달하는 것이다.

### 2.7.1 커스텀 데이터셋(Custsom Dataset)
그런데 torch.utils.data.Dataset을 상속받아 직접 커스텀 데이터셋을 만드는 경우도 있다. torch.utils.data.Datset은 파이토치에서 데이터셋을 제공하는 추상 클래스이다. Dataset을 상속받아 다음 메소드들을 오버라이드 하여 커스텀 데이터셋을 만들어보겠다.

In [ ]:
# 커스텀 데이터셋을 만들 때, 일단 가장 기본적인 뼈대는 아래와 같다. 여기서 필요한 기본적인 define 은 3개이다.


In [ ]:
class CustomDataset(torch.utils.data.Dataset): 
  def __init__(self):return
#  데이터셋의 전처리를 해주는 부분

  def __len__(self):return
#  데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분

  def __getitem__(self, idx):return
#  데이터셋에서 특정 1개의 샘플을 가져오는 함수

In [ ]:
# len(dataset)을 했을 때 데이터셋의 크기를 return 할 len

# dataset[i]를 했을 때 i번재 샘플을 가져오도록 하는 인덱싱을 위한 get_item

### 2.7.2 커스텀 데이터으로 선형회귀 구현하기


In [ ]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset): 
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [ ]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [ ]:
model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 44199.386719
Epoch    0/20 Batch 2/3 Cost: 18326.742188
Epoch    0/20 Batch 3/3 Cost: 5618.166504
Epoch    1/20 Batch 1/3 Cost: 1294.254883
Epoch    1/20 Batch 2/3 Cost: 460.197510
Epoch    1/20 Batch 3/3 Cost: 192.675720
Epoch    2/20 Batch 1/3 Cost: 35.667679
Epoch    2/20 Batch 2/3 Cost: 14.944163
Epoch    2/20 Batch 3/3 Cost: 0.434156
Epoch    3/20 Batch 1/3 Cost: 3.636916
Epoch    3/20 Batch 2/3 Cost: 2.199007
Epoch    3/20 Batch 3/3 Cost: 0.002766
Epoch    4/20 Batch 1/3 Cost: 1.721153
Epoch    4/20 Batch 2/3 Cost: 0.398790
Epoch    4/20 Batch 3/3 Cost: 2.327561
Epoch    5/20 Batch 1/3 Cost: 1.248785
Epoch    5/20 Batch 2/3 Cost: 1.354533
Epoch    5/20 Batch 3/3 Cost: 2.051692
Epoch    6/20 Batch 1/3 Cost: 2.236589
Epoch    6/20 Batch 2/3 Cost: 0.235299
Epoch    6/20 Batch 3/3 Cost: 1.027871
Epoch    7/20 Batch 1/3 Cost: 1.193879
Epoch    7/20 Batch 2/3 Cost: 1.408593
Epoch    7/20 Batch 3/3 Cost: 0.411535
Epoch    8/20 Batch 1/3 Cost: 0.051273
Epoch

In [ ]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.5672]], grad_fn=<AddmmBackward>)
